# Generated by Django 4.1.7 on 2023-04-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_name',
            new_name='user',
        ),
    ]
