# Generated by Django 4.1.7 on 2023-04-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_posts_options_alter_posts_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
