# Generated by Django 4.1.7 on 2023-04-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-time_create'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
    ]
