# Generated by Django 4.1.7 on 2023-03-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='preview/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
