# Generated by Django 4.1.7 on 2023-04-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='content',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
