# Generated by Django 4.1.7 on 2023-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='Art-images/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Art',
                'verbose_name_plural': 'Arts',
                'ordering': ['-time_create'],
            },
        ),
    ]
