# Generated by Django 4.1.7 on 2023-04-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
