# Generated by Django 4.1.7 on 2023-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_alter_arts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
