# Generated by Django 4.1.7 on 2023-04-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('arts', '0003_alter_arts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='Category'),
        ),
    ]
